version: '2'

services:
  wpe:
    restart: always
    build: ./wpe
    privileged: true
    ports:
      - 8080:8080
  backend:
    restart: always
    build: ./backend
    privileged: true
    ports:
      - 1337:1337
